USE HOSPITAL;
-- (i.1). Xem danh sách bác sĩ trực tại một ca trong một ngày ở một khoa.
SELECT CONCAT(HO, TEN) AS HOVATEN
FROM BACSI
         JOIN NHANVIEN N on BACSI.MA_BS = N.MA_NV
         JOIN TGLAMVIEC T on N.MA_NV = T.MA_NV
         JOIN KHOADIEUTRI K on N.MA_KHOA = K.MA_KHOA
WHERE T.CA_LAM_VIEC = '1'
  AND T.NGAY_LAM_VIEC = '20-11-2020'
  AND TEN_KHOA = 'KHOA NOI';

-- (i.2). Xem danh sách bác sĩ trực trong một ngày ở một khoa.
SELECT CONCAT(HO, TEN) AS HOVATEN
FROM BACSI
         JOIN NHANVIEN N on BACSI.MA_BS = N.MA_NV
         JOIN TGLAMVIEC T on N.MA_NV = T.MA_NV
         JOIN KHOADIEUTRI K on N.MA_KHOA = K.MA_KHOA
WHERE T.NGAY_LAM_VIEC = '20-11-2020'
  AND TEN_KHOA = 'KHOA NOI';

-- (i.3). Xem danh sách bác sĩ trực tại một ca trong một ngày ở tất cả các khoa.
SELECT CONCAT(HO, TEN) AS HOVATEN
FROM BACSI
         JOIN NHANVIEN N on BACSI.MA_BS = N.MA_NV
         JOIN TGLAMVIEC T on N.MA_NV = T.MA_NV
WHERE T.CA_LAM_VIEC = '1';

-- (i.4). Xem danh sách bác sĩ trực trong một ngày ở tất cả các khoa.
SELECT CONCAT(HO, TEN) AS HOVATEN
FROM BACSI
         JOIN NHANVIEN N on BACSI.MA_BS = N.MA_NV
         JOIN TGLAMVIEC T on N.MA_NV = T.MA_NV
WHERE T.NGAY_LAM_VIEC = '20-11-2020';

-- (i.5). Xem tổng số bệnh nhân tại một ca trong một ngày ở một khoa.
DROP VIEW IF EXISTS KHAMNOI;
CREATE VIEW KHAMNOI AS
SELECT K.MA_KHAM
FROM KBNOITRU
         JOIN KHAMBENH K on KBNOITRU.MA_KHAM = K.MA_KHAM
         JOIN BACSI B on B.MA_BS = KBNOITRU.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
         JOIN KHOADIEUTRI K2 on N.MA_KHOA = K2.MA_KHOA
WHERE CA_KHAM = '1'
  AND THOI_GIAN_KHAM = '20-11-2020'
  AND TEN_KHOA = 'KHOA NOI';
DROP VIEW IF EXISTS KHAMNGOAI;
CREATE VIEW KHAMNGOAI AS
SELECT K.MA_KHAM
FROM KBNGOAITRU
         JOIN KHAMBENH K on KBNGOAITRU.MA_KHAM = K.MA_KHAM
         JOIN BACSI B on B.MA_BS = KBNGOAITRU.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
         JOIN KHOADIEUTRI K2 on N.MA_KHOA = K2.MA_KHOA
WHERE CA_KHAM = '1'
  AND THOI_GIAN_KHAM = '20-11-2020'
  AND TEN_KHOA = 'KHOA NOI';

SELECT ((SELECT COUNT(*) FROM KHAMNGOAI) + (SELECT COUNT(*) FROM KHAMNOI)) AS TONGSOBENHNHAN;

-- (i.6). Xem tổng số bệnh nhân nội trú nhập viện trong một ca trong một ngày ở một khoa.
SELECT COUNT(*) AS TONGSOBENHNHAN
FROM BENHANNOITRU
         JOIN BACSI B on B.MA_BS = BENHANNOITRU.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
         JOIN KHOADIEUTRI K on N.MA_KHOA = K.MA_KHOA
WHERE THOIGIANNHAPVIEN = '20-11-2020'
  AND CA_LAM_VIEC = '1'
  AND TEN_KHOA = 'KHOA NOI';

-- (i.7). Xem tổng số bệnh nhân ngoại trú trong một ca trong một ngày ở một khoa.
SELECT COUNT(*) AS TONGSOBENHNHAN
FROM KBNGOAITRU
         JOIN KHAMBENH K on K.MA_KHAM = KBNGOAITRU.MA_KHAM
         JOIN BACSI B on B.MA_BS = KBNGOAITRU.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
         JOIN KHOADIEUTRI K2 on N.MA_KHOA = K2.MA_KHOA
WHERE CA_KHAM = '1'
  AND THOI_GIAN_KHAM = '20-11-2020'
  AND TEN_KHOA = 'KHOA NOI';

-- (i.9). Xem tổng số bệnh nhân nội trú nhập viện trong một ca trong một ngày ở tất cả các khoa.
SELECT COUNT(*) AS TONGSOBENHNHAN
FROM BENHANNOITRU
         JOIN BACSI B on B.MA_BS = BENHANNOITRU.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
WHERE THOIGIANNHAPVIEN = '20-11-2020'
  AND CA_LAM_VIEC = '1';
-- (i.10). Xem tổng số bệnh nhân ngoại trú trong một ca trong một ngày ở tất cả các khoa.
SELECT COUNT(*) AS TONGSOBENHNHAN
FROM KBNGOAITRU
         JOIN KHAMBENH K on K.MA_KHAM = KBNGOAITRU.MA_KHAM
WHERE CA_KHAM = '1'
  AND THOI_GIAN_KHAM = '20-11-2020';


-- (i.11). Xem tổng số xét nghiệm được làm trong một ngày ở một khoa.
DROP VIEW IF EXISTS NGOAIXN;
CREATE VIEW NGOAIXN AS
SELECT MA_XN, TEN_KHOA, THOIGIANXN
FROM XN
         JOIN KHAMBENH K on XN.MA_KHAM = K.MA_KHAM
         JOIN KBNGOAITRU K2 on K.MA_KHAM = K2.MA_KHAM
         JOIN BACSI B on B.MA_BS = K2.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
         JOIN KHOADIEUTRI K3 on N.MA_KHOA = K3.MA_KHOA;
DROP VIEW IF EXISTS NOIXN;
CREATE VIEW NOIXN AS
SELECT MA_XN, TEN_KHOA, THOIGIANXN
FROM XN
         JOIN KHAMBENH K on XN.MA_KHAM = K.MA_KHAM
         JOIN KBNOITRU K2 on K.MA_KHAM = K2.MA_KHAM
         JOIN BACSI B on B.MA_BS = K2.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
         JOIN KHOADIEUTRI K3 on N.MA_KHOA = K3.MA_KHOA;

SELECT ((SELECT COUNT(*) FROM NGOAIXN WHERE TEN_KHOA = 'KHOA NOI' AND THOIGIANXN = '20-11-2020') +
        (SELECT COUNT(*) FROM NOIXN WHERE TEN_KHOA = 'KHOA NOI' AND THOIGIANXN = '20-11-2020')) AS TONGXN;

-- (i.12). Xem tổng số xét nghiệm được làm trong một ngày ở tất cả các khoa.
DROP VIEW IF EXISTS NGOAIXN;
CREATE VIEW NGOAIXN AS
SELECT MA_XN, TEN_KHOA, THOIGIANXN
FROM XN
         JOIN KHAMBENH K on XN.MA_KHAM = K.MA_KHAM
         JOIN KBNGOAITRU K2 on K.MA_KHAM = K2.MA_KHAM
         JOIN BACSI B on B.MA_BS = K2.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
         JOIN KHOADIEUTRI K3 on N.MA_KHOA = K3.MA_KHOA;
DROP VIEW IF EXISTS NOIXN;
CREATE VIEW NOIXN AS
SELECT MA_XN, TEN_KHOA, THOIGIANXN
FROM XN
         JOIN KHAMBENH K on XN.MA_KHAM = K.MA_KHAM
         JOIN KBNOITRU K2 on K.MA_KHAM = K2.MA_KHAM
         JOIN BACSI B on B.MA_BS = K2.MA_BS
         JOIN NHANVIEN N on B.MA_BS = N.MA_NV
         JOIN KHOADIEUTRI K3 on N.MA_KHOA = K3.MA_KHOA;

SELECT ((SELECT COUNT(*) FROM NGOAIXN WHERE THOIGIANXN = '20-11-2020') +
        (SELECT COUNT(*) FROM NOIXN WHERE THOIGIANXN = '20-11-2020')) AS TONGXN;

-- (iii). Bệnh nhân
-- (iii.1). Cập nhật thông tin nhân khẩu học và thông tin bảo hiểm y tế.
UPDATE BENHNHAN
SET TUOI = 20, DAN_TOC = 'KINH',  NGHE_NGHIEP = 'LAM RUONG'
WHERE MA_BN = '1';
UPDATE BHYT
SET MA_THE = '123', THOI_HAN = 20/12/2020, NOI_DANG_KY = 'THU DUC'
WHERE BN = '1';
-- (iii.2). Xem danh sách các thuốc mà mình đã dùng trong lần điều trị gần nhất.
DROP VIEW IF EXISTS KHAMBENHGANNHAT;
CREATE VIEW KHAMBENHGANNHAT AS
SELECT DISTINCT KHAMBENH.MA_KHAM, HOVATEN, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNOITRU
                         JOIN BACSI B2 on KBNOITRU.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)
               UNION
               (SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNGOAITRU
                         JOIN BACSI B2 on KBNGOAITRU.MA_BS = B2.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111'
ORDER BY THOI_GIAN_KHAM DESC
LIMIT 1;
SELECT TEN_THUOC
FROM CHEDOTHUOC
         JOIN KQCHANDOAN K on CHEDOTHUOC.MA_CHANDOAN = K.MA_CHANDOAN and CHEDOTHUOC.MA_BENH = K.MA_BENH and
                              CHEDOTHUOC.MA_KHAM = K.MA_KHAM
         JOIN THUOC T on CHEDOTHUOC.MA_THUOC = T.MA_THUOC
         JOIN KHAMBENHGANNHAT K2 on CHEDOTHUOC.MA_KHAM = K2.MA_KHAM;


-- (iii.3). Xem danh sách các thuốc mà mình đã dùng trong tất cả các lần điều trị.
DROP VIEW IF EXISTS CACMAKHAMBENH;
CREATE VIEW CACMAKHAMBENH AS
SELECT DISTINCT KHAMBENH.MA_KHAM, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN FROM KBNOITRU) UNION (SELECT MA_KHAM, MA_BN FROM KBNGOAITRU)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111';

SELECT TEN_THUOC
FROM CHEDOTHUOC
         JOIN KQCHANDOAN K on CHEDOTHUOC.MA_CHANDOAN = K.MA_CHANDOAN and CHEDOTHUOC.MA_BENH = K.MA_BENH and
                              CHEDOTHUOC.MA_KHAM = K.MA_KHAM
         JOIN THUOC T on CHEDOTHUOC.MA_THUOC = T.MA_THUOC
         JOIN KHAMBENHGANNHAT K2 on CHEDOTHUOC.MA_KHAM = K2.MA_KHAM;


-- (iii.4). Xem kết quả xét nghiệm trong lần điều trị gần nhất.
DROP VIEW IF EXISTS CACMAKHAMBENH;
CREATE VIEW CACMAKHAMBENH AS
SELECT DISTINCT KHAMBENH.MA_KHAM, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN FROM KBNOITRU) UNION (SELECT MA_KHAM, MA_BN FROM KBNGOAITRU)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111';

SELECT GIA_TRI
FROM CHISO
         JOIN XN X on CHISO.MA_XN = X.MA_XN and CHISO.MA_KHAM = X.MA_KHAM
         JOIN CACMAKHAMBENH C on CHISO.MA_KHAM = C.MA_KHAM;

-- (iii.5). Xem danh sách tất cả các xét nghiệm mà mình đã làm.
DROP VIEW IF EXISTS CACMAKHAMBENH;
CREATE VIEW CACMAKHAMBENH AS
SELECT DISTINCT KHAMBENH.MA_KHAM, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN FROM KBNOITRU) UNION (SELECT MA_KHAM, MA_BN FROM KBNGOAITRU)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111';

SELECT TEN_XN
FROM XN
         JOIN CACMAKHAMBENH C on XN.MA_KHAM = C.MA_KHAM;

-- (iii.6). Xem danh sách tất cả các xét nghiệm có ghi chú “bất thường” của một chỉ số xét nghiệm mà mình đã làm.
DROP VIEW IF EXISTS CACMAKHAMBENH;
CREATE VIEW CACMAKHAMBENH AS
SELECT DISTINCT KHAMBENH.MA_KHAM, HOVATEN, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNOITRU
                         JOIN BACSI B2 on KBNOITRU.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)
               UNION
               (SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNGOAITRU
                         JOIN BACSI B2 on KBNGOAITRU.MA_BS = B2.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111';
SELECT GHI_CHU
FROM CHISO
         JOIN CACMAKHAMBENH C on CHISO.MA_KHAM = C.MA_KHAM
WHERE GHI_CHU = 'BAT THUONG';
-- (iii.7). Xem danh sách bác sĩ đã điều trị trong lần điều trị gần nhất.
DROP VIEW IF EXISTS KHAMBENHGANNHAT;
CREATE VIEW KHAMBENHGANNHAT AS
SELECT DISTINCT KHAMBENH.MA_KHAM, HOVATEN, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNOITRU
                         JOIN BACSI B2 on KBNOITRU.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)
               UNION
               (SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNGOAITRU
                         JOIN BACSI B2 on KBNGOAITRU.MA_BS = B2.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111'
ORDER BY THOI_GIAN_KHAM DESC
LIMIT 1;
SELECT HOVATEN
FROM HOSPITAL.KHAMBENHGANNHAT;
-- (iii.8). Xem danh sách bác sĩ đã điều trị trong tất cả các lần điều trị.
DROP VIEW IF EXISTS CACMAKHAMBENH;
CREATE VIEW CACMAKHAMBENH AS
SELECT DISTINCT KHAMBENH.MA_KHAM, HOVATEN, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNOITRU
                         JOIN BACSI B2 on KBNOITRU.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)
               UNION
               (SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNGOAITRU
                         JOIN BACSI B2 on KBNGOAITRU.MA_BS = B2.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111';
SELECT HOVATEN
FROM HOSPITAL.CACMAKHAMBENH;
-- (iii.9). Xem chế độ dinh dưỡng nếu được chỉ định trong lần điều trị gần nhất.
DROP VIEW IF EXISTS KHAMBENHGANNHAT;
CREATE VIEW KHAMBENHGANNHAT AS
SELECT DISTINCT KHAMBENH.MA_KHAM, HOVATEN, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNOITRU
                         JOIN BACSI B2 on KBNOITRU.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)
               UNION
               (SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNGOAITRU
                         JOIN BACSI B2 on KBNGOAITRU.MA_BS = B2.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111'
ORDER BY THOI_GIAN_KHAM DESC
LIMIT 1;
SELECT C.NOI_DUNG
FROM DINHDUONG
         JOIN CDDD C on C.MA_CDDD = DINHDUONG.MA_CDDD
         JOIN KQCHANDOAN K on DINHDUONG.MA_CHANDOAN = K.MA_CHANDOAN and DINHDUONG.MA_BENH = K.MA_BENH and
                              DINHDUONG.MA_KHAM = K.MA_KHAM
         JOIN KHAMBENHGANNHAT K2 on DINHDUONG.MA_KHAM = K2.MA_KHAM;
-- (iii.10). Xem danh sách chế độ dinh dưỡng nếu được chỉ định trong tất cả các lần điều trị.
DROP VIEW IF EXISTS CACMAKHAMBENH;
CREATE VIEW CACMAKHAMBENH AS
SELECT DISTINCT KHAMBENH.MA_KHAM, HOVATEN, THOI_GIAN_KHAM
FROM KHAMBENH
         JOIN ((SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNOITRU
                         JOIN BACSI B2 on KBNOITRU.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)
               UNION
               (SELECT MA_KHAM, MA_BN, CONCAT(HO, TEN) AS HOVATEN
                FROM KBNGOAITRU
                         JOIN BACSI B2 on KBNGOAITRU.MA_BS = B2.MA_BS = B2.MA_BS
                         JOIN NHANVIEN N on B2.MA_BS = N.MA_NV)) AS B
              ON KHAMBENH.MA_KHAM = B.MA_KHAM
WHERE MA_BN = '1111111';
SELECT C.NOI_DUNG
FROM DINHDUONG
         JOIN CDDD C on C.MA_CDDD = DINHDUONG.MA_CDDD
         JOIN KQCHANDOAN K on DINHDUONG.MA_CHANDOAN = K.MA_CHANDOAN and DINHDUONG.MA_BENH = K.MA_BENH and
                              DINHDUONG.MA_KHAM = K.MA_KHAM
         JOIN HOSPITAL.CACMAKHAMBENH K2 on DINHDUONG.MA_KHAM = K2.MA_KHAM;



-- bs
-- 1
USE HOSPITAL;
UPDATE KHAMBENH
SET THOI_GIAN_KHAM = '1' AND CA_KHAM = '1'
WHERE KHAMBENH.MA_KHAM = (SELECT O.MA_KHAM
                          FROM KBNGOAITRU O
                          WHERE O.MA_BS = '321'
                            AND O.MA_BN = '123');

-- 2
UPDATE KHAMBENH
SET THOI_GIAN_KHAM = '1' AND CA_KHAM = '1'
WHERE KHAMBENH.MA_KHAM = (SELECT O.MA_KHAM
                          FROM KBNGOAITRU O
                          WHERE O.MA_BS = '321'
                            AND O.MA_BN = '123');

-- 3
SELECT *
FROM BENHNHAN
WHERE BENHNHAN.MA_BN IN (SELECT K.MA_BN
                         FROM (SELECT * FROM KBNGOAITRU UNION SELECT * FROM KBNOITRU) AS K
                                  JOIN KHAMBENH KB ON K.MA_KHAM = KB.MA_KHAM
                         WHERE (K.MA_BS = '123' AND KB.THOI_GIAN_KHAM = 10 / 10 / 1000));

-- 4
SELECT *
FROM KHAMBENH K
         JOIN KQCHANDOAN C ON K.MA_KHAM = C.MA_KHAM
WHERE K.MA_KHAM IN (SELECT K.MA_KHAM
                    FROM (SELECT * FROM KBNGOAITRU UNION SELECT * FROM KBNOITRU) K
                    WHERE K.MA_BN = '123');

-- 5
SELECT TEN_THUOC, THOI_GIAN_DUNG
FROM THUOC T
         JOIN CHEDOTHUOC C ON T.MA_THUOC = C.MA_THUOC
         JOIN KQCHANDOAN KQ ON KQ.MA_CHANDOAN = C.MA_CHANDOAN
         JOIN KHAMBENH K ON KQ.MA_KHAM = K.MA_KHAM
WHERE K.MA_KHAM IN (SELECT K.MA_KHAM
                    FROM (SELECT * FROM KBNGOAITRU UNION SELECT * FROM KBNOITRU) K
                    WHERE K.MA_BN = '123');

-- 6
SELECT MA_XN, TEN_XN
FROM XN
         JOIN KHAMBENH K ON XN.MA_KHAM = K.MA_KHAM
WHERE K.MA_KHAM IN (SELECT K.MA_KHAM
                    FROM (SELECT * FROM KBNGOAITRU UNION SELECT * FROM KBNOITRU) K
                    WHERE K.MA_BN = '123');

-- 7
SELECT MA_PHIM, LOAI_PHIM, THOI_GIAN_CHUP, MA_BS, NHAN_XET
FROM PHIM P
         JOIN KHAMBENH K ON P.MA_KHAM = K.MA_KHAM
WHERE K.MA_KHAM IN (SELECT K.MA_KHAM
                    FROM (SELECT * FROM KBNGOAITRU UNION SELECT * FROM KBNOITRU) K
                    WHERE K.MA_BN = '123');

-- 8
SELECT *
FROM BENHNHAN
WHERE MA_BN IN
      (SELECT KB.MA_BN
       FROM (SELECT * FROM KBNGOAITRU UNION SELECT * FROM KBNOITRU) KB
                JOIN BENHNHAN B ON B.MA_BN = KB.MA_BN
                JOIN KHAMBENH K ON K.MA_KHAM = KB.MA_KHAM
                JOIN KQCHANDOAN C ON K.MA_KHAM = C.MA_KHAM
       WHERE KB.MA_BS = '123'
       GROUP BY MA_BENH);

-- 9
SELECT *
FROM BENHNHAN
WHERE MA_BN IN
      (SELECT KB.MA_BN
       FROM (SELECT * FROM KBNGOAITRU UNION SELECT * FROM KBNOITRU) KB
                JOIN BENHNHAN B ON B.MA_BN = KB.MA_BN
                JOIN KHAMBENH K ON K.MA_KHAM = KB.MA_KHAM
                JOIN KQCHANDOAN C ON K.MA_KHAM = C.MA_KHAM
                JOIN XN ON XN.MA_KHAM = KB.MA_KHAM
                JOIN CHISO CS ON CS.MA_XN = XN.MA_XN
                JOIN CHISOXN CXN ON CXN.MA_CHISOXN = CS.MA_CHISOXN
       WHERE KB.MA_BS = '123'
         AND MA_BENH = '234'
         AND (CS.GIA_TRI > CXN.UPPERBOUND OR CS.GIA_TRI < CXN.LOWERBOUND));

-- 10
SELECT *
FROM BENHNHAN
WHERE MA_BN IN
      (SELECT MA_BN
       FROM BACSI B
                JOIN BENHANNOITRU A ON B.MA_BS = A.MA_BS
       WHERE TG_XV IS NOT NULL);

-- 12
-- CREATE VIEW KQXN AS
-- SELECT * FROM (SELECT * FROM KBNGOAITRU UNION SELECT * FROM KBNOITRU) KB 
-- JOIN BENHNHAN B ON B.MA_BN = KB.MA_BN 
-- JOIN KHAMBENH K ON K.MA_KHAM = KB.MA_KHAM 
-- JOIN XN ON XN.MA_KHAM = KB.MA_KHAM
-- JOIN CHISO CS ON CS.MA_XN = XN.MA_XN
-- JOIN CHISOXN CXN ON CXN.MA_CHISOXN = CS.MA_CHISOXN
-- WHERE KB.MA_BS = '123'
-- GROUP BY MA_BN
-- ORDER BY THOIGIANXN DESC;


